_wandb:
    value:
        cli_version: 0.24.0
        e:
            8umqq3wvkorep3pckwuo8srr0cv3pcd5:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "4294967296"
                codePath: search.py
                codePathLocal: search.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "387824791552"
                email: coolu0811@163.com
                executable: /Users/caolu/opt/anaconda3/envs/multi/bin/python
                git:
                    commit: 9bf4a0720692fbe865aa55e1811be80b7022f663
                    remote: git@github.com:Coolu-001/AI-Lab5.git
                host: coolus-MacBook-Air-2.local
                memory:
                    total: "8589934592"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/caolu/Desktop/AI_Lab5/search.py
                python: CPython 3.11.14
                root: /Users/caolu/Desktop/AI_Lab5
                startedAt: "2026-01-17T11:47:18.185200Z"
                writerId: 8umqq3wvkorep3pckwuo8srr0cv3pcd5
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.24.0
            "6": 4.47.1
            "10":
                - 20
            "12": 0.24.0
            "13": darwin-arm64
batch_size:
    value: 16
dropout:
    value: 0.2
lr:
    value: 1e-05
output_hidden_size:
    value: 128
resnet_type:
    value: 18
