_wandb:
    value:
        cli_version: 0.24.0
        e:
            qg63wyok4bltivsc9b9d9x7k5u1wux2p:
                codePath: search.py
                codePathLocal: search.py
                email: coolu0811@163.com
                executable: /Users/caolu/opt/anaconda3/envs/multi/bin/python
                git:
                    commit: ee7f801a255d0e2a591b28898dbf64e9995f5c55
                    remote: git@github.com:Coolu-001/AI-Lab5.git
                host: coolus-Air-2.lan
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/caolu/Desktop/AI_Lab5/search.py
                python: CPython 3.11.14
                root: /Users/caolu/Desktop/AI_Lab5
                startedAt: "2026-01-17T14:26:20.357935Z"
                writerId: qg63wyok4bltivsc9b9d9x7k5u1wux2p
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.24.0
            "6": 4.47.1
            "10":
                - 20
            "12": 0.24.0
            "13": darwin-arm64
batch_size:
    value: 16
dropout:
    value: 0.2
lr:
    value: 1e-05
output_hidden_size:
    value: 128
