_wandb:
    value:
        cli_version: 0.24.0
        e:
            6gtiqd32afie273phkcfey4c057yh5w5:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "5368709120"
                args:
                    - --roberta_lr
                    - "2e-6"
                    - --clip_lr
                    - "1e-6"
                    - --lr
                    - "8e-5"
                    - --roberta_dropout
                    - "0.4"
                    - --clip_dropout
                    - "0.4"
                    - --fusion_dropout
                    - "0.5"
                    - --weight_decay
                    - "0.05"
                    - --model
                    - "3"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "386495684608"
                email: coolu0811@163.com
                executable: /Users/caolu/opt/anaconda3/envs/multi/bin/python
                git:
                    commit: ee7f801a255d0e2a591b28898dbf64e9995f5c55
                    remote: git@github.com:Coolu-001/AI-Lab5.git
                host: coolus-Air-2.lan
                memory:
                    total: "8589934592"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/caolu/Desktop/AI_Lab5/main.py
                python: CPython 3.11.14
                root: /Users/caolu/Desktop/AI_Lab5
                startedAt: "2026-01-19T10:27:31.730021Z"
                writerId: 6gtiqd32afie273phkcfey4c057yh5w5
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.14
            "5": 0.24.0
            "6": 4.47.1
            "10":
                - 20
            "12": 0.24.0
            "13": darwin-arm64
attention_dropout:
    value: 0.3
attention_nheads:
    value: 8
batch_size:
    value: 16
clip_dropout:
    value: 0.4
clip_lr:
    value: 1e-06
fusion_dropout:
    value: 0.5
image_only:
    value: false
lr:
    value: 8e-05
middle_hidden_size:
    value: 768
model:
    value: 3
output_hidden_size:
    value: 256
roberta_dropout:
    value: 0.4
roberta_lr:
    value: 2e-06
text_only:
    value: false
weight_decay:
    value: 0.05
