_wandb:
    value:
        cli_version: 0.24.0
        e:
            kr9lw3iqrgkvm0a4an6k00fiw894610b:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "3221225472"
                args:
                    - --batch_size
                    - "32"
                    - --roberta_dropout
                    - "0.2"
                    - --roberta_lr
                    - "2e-5"
                    - --middle_hidden_size
                    - "512"
                    - --resnet_type
                    - "50"
                    - --resnet_dropout
                    - "0.2"
                    - --resnet_lr
                    - "2e-5"
                    - --attention_nheads
                    - "12"
                    - --attention_dropout
                    - "0.2"
                    - --fusion_dropout
                    - "0.2"
                    - --output_hidden_size
                    - "512"
                    - --weight_decay
                    - "1e-4"
                    - --lr
                    - "2e-5"
                    - --text_only
                    - --model
                    - "3"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "385521352704"
                email: coolu0811@163.com
                executable: /Users/caolu/opt/anaconda3/envs/multi/bin/python
                host: coolus-MacBook-Air-2.local
                memory:
                    total: "8589934592"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/caolu/Desktop/AILAB5-main/main.py
                python: CPython 3.11.14
                root: /Users/caolu/Desktop/AILAB5-main
                startedAt: "2026-01-16T09:03:56.106562Z"
                writerId: kr9lw3iqrgkvm0a4an6k00fiw894610b
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.24.0
            "6": 4.47.1
            "10":
                - 20
            "12": 0.24.0
            "13": darwin-arm64
attention_dropout:
    value: 0.2
attention_nheads:
    value: 12
batch_size:
    value: 32
fusion_dropout:
    value: 0.2
lr:
    value: 2e-05
middle_hidden_size:
    value: 512
output_hidden_size:
    value: 512
resnet_dropout:
    value: 0.2
resnet_lr:
    value: 2e-05
resnet_type:
    value: 50
roberta_dropout:
    value: 0.2
roberta_lr:
    value: 2e-05
weight_decay:
    value: 0.0001
