_wandb:
    value:
        cli_version: 0.24.0
        e:
            aki196ib0e24stdece77ube9gylv8oj8:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "3221225472"
                args:
                    - --model
                    - "2"
                    - --text_only
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "400770560000"
                email: coolu0811@163.com
                executable: /Users/caolu/opt/anaconda3/envs/multi/bin/python
                git:
                    commit: 915e0e01fe71251dc9bfbea1f423effe4dd180fb
                    remote: https://github.com/Coolu-001/AI-Lab5.git
                host: coolus-MacBook-Air-2.local
                memory:
                    total: "8589934592"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/caolu/Desktop/AI-Lab5-clip-base3/main.py
                python: CPython 3.11.14
                root: /Users/caolu/Desktop/AI-Lab5-clip-base3
                startedAt: "2026-01-27T14:08:56.020709Z"
                writerId: aki196ib0e24stdece77ube9gylv8oj8
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.24.0
            "6": 4.47.1
            "10":
                - 20
            "12": 0.24.0
            "13": darwin-arm64
attention_dropout:
    value: 0.4
attention_nheads:
    value: 8
batch_size:
    value: 16
clip_dropout:
    value: 0.4
clip_lr:
    value: 1e-06
fusion_dropout:
    value: 0.5
image_only:
    value: false
lr:
    value: 0.0001
middle_hidden_size:
    value: 768
model:
    value: 2
output_hidden_size:
    value: 256
roberta_dropout:
    value: 0.4
roberta_lr:
    value: 2e-05
text_only:
    value: true
weight_decay:
    value: 0.05
